spring:
  application:
    name: rocketmq-consumer
  cloud:
    stream:
      rocketmq:
        binder:
          namesrv-addr: 192.168.32.128:9876
        bindings:
          input: {consumer.orderly: true}
      # 定义name为input11/input22/input33的binding
      bindings:
        input11: {destination: test-topic-1, content-type: text/plain, group: test-group, consumer.maxAttempts: 1}
        input22: {destination: test-topic-2, content-type: text/plain, group: test-group, consumer.maxAttempts: 1}
        input33: {destination: test-topic-3, content-type: text/plain, group: test-group, consumer.maxAttempts: 1}

server:
  port: 9094

management:
  endpoints:
    web:
      exposure:
        include: '*'