spring:
  application:
    name: rocketmq-provider
  cloud:
    stream:
      rocketmq:
        binder:
          # RocketMQ 服务器地址
          namesrv-addr: 192.168.32.128:9876
      bindings:
        # # 定义name为output1/output2/output3的binding
        # 这里是个 Map 类型参数，{} 为 YAML 中 Map 的行内写法
        # 运行成功后即可在 RocketMQ 控制台的 消息 列表中选择 test-topic 主题即可看到发送的消息
        output1: {destination: test-topic-1, content-type: application/json}
        output2: {destination: test-topic-2, content-type: application/json}
        output3: {destination: test-topic-3, content-type: application/json}
server:
  port: 9093

management:
  endpoints:
    web:
      exposure:
        include: '*'