spring:
  application:
    name: hello-spring-cloud-eureka # 根据这个命名找到这个注册发现服务,所以名字很重要,要起名
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # 通过 eureka.client.registerWithEureka:false 和 fetchRegistry:false 来表明自己是一个 Eureka Server,
    # 不加这两个属性配置的话,会认为你是Eureka client.
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 每一个Eureka Client实例注册之后需要向注册中心Eureka Server发送心跳
