spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        # Nacos服务注册中心的地址
        server-addr: 127.0.0.1:8848

server:
  port: 8081

# 健康检查端点
management:
  endpoints:
    web:
      exposure:
        include: "*"