spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/xuzhijiang/spring-cloud-config
          search-paths: respo
          username: your username
          password: your pwd

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# 相关配置说明，如下：

#spring.cloud.config.label：配置仓库的分支
#spring.cloud.config.server.git.uri：配置 Git 仓库地址（GitHub、GitLab、码云 ...）
#spring.cloud.config.server.git.search-paths：配置仓库路径（存放配置文件的目录）
#spring.cloud.config.server.git.username：访问 Git 仓库的账号
#spring.cloud.config.server.git.password：访问 Git 仓库的密码

#注意事项：
#
#如果使用 GitLab 作为仓库的话，git.uri 需要在结尾加上 .git，GitHub 则不用