server:
  port: 7001

eureka:
  instance:
    # eureka服务端的主机名称,注意不能与7002,7003相同，所以要做映射配置
    hostname: eureka7001
    # windows上要修改C:\Windows\System32\drivers\etc\host文件,
    # 127.0.0.1 eureka7001.com
    # 127.0.0.1 eureka7002.com
    # 127.0.0.1 eureka7003.com
  client:
    # false表示不向eureka Server服务注册中心注册,因为自己就是EurekaServer,所以不用自己注册.
    register-with-eureka: false
    # false表示:我的职责就是维护服务实例，并不需要从eureka Server上抓取服务,因为自己就是EurekaServer
    fetch-registry: false
    service-url:
      # 单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/