spring:
  application:
    name: sendmail
  mail:
    # 邮件发送服务器的主机，这里采用的是sina邮箱来发送邮件
    host: smtp.qq.com
    # 邮件发送服务器的端口
    # port: 465
    # smtp是邮件发送协议，pop3和imap是邮件接收协议。因为我们要发送邮件，因此是smtp
    protocol: smtp
    # 邮件发送服务器的用户名
    username: 2233835996@qq.com
    # spring.mail.password指的是该邮箱的授权码，而不是该邮箱的密码
    password: xxxxxxxxxxxxxx
    # 一般情况下，发送邮件都是要进行验证
    # auth: true
    properties:
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      # 一般情况下，发送邮件都是要进行验证
      mail.smtp.auth: true
      mail.debug: true
      mail.smtp.ssl.enable: true
  freemarker:
    suffix: .html
    cache: false
    settings:
      output_format: HTMLOutputFormat
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 9090
