spring:
  freemarker:
    allowRequestOverride: false
    allowSessionOverride: false
    cache: true
    checkTemplateLocation: true
    contentType: text/html
    exposeRequestAttributes: false
    exposeSessionAttributes: false
    exposeSpringMacroHelpers: false
    suffix: .ftl
    charset: UTF-8
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/  #表示所有的模板文件都放在该目录下,comma-separated list
    settings:
      locale: zh_CN
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss