server:
  port: 3344

spring:
  application:
    name:  myspringapp-name
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuzhijiang/microservicecloud-config/
#          username:
#          password: