server:
  port: 9090

spring:
  datasource:
    hikari:
      db1:
        jdbcUrl: jdbc:hsqldb:mem:db1
        username: sa
        password:
        driverClassName: org.hsqldb.jdbc.JDBCDriver
      db2:
        jdbcUrl: jdbc:hsqldb:mem:db2
        username: sa
        password:
        driverClassName: org.hsqldb.jdbc.JDBCDriver