spring:
  application:
    name: data-multidatasource
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    jdbcUrl: jdbc:hsqldb:mem:db1
    username: sa
    password:
  second-datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    jdbcUrl: jdbc:hsqldb:mem:db2
    username: sa
    password:

server:
  port: 9090
