spring:
  application:
    name: hello-spring-cloud-config-client
  cloud:
    config:
      uri: http://localhost:8888 # spring cloud config的地址.
      name: config-client # 加载的配置文件名.
      label: master # 加载哪个分支
      profile: dev # 加载哪个环境的,这里是开发环境

# 相关配置说明，如下：

#spring.cloud.config.uri：配置服务中心的网址
#spring.cloud.config.name：配置文件名称的前缀
#spring.cloud.config.label：配置仓库的分支
#spring.cloud.config.profile：配置文件的环境标识
  #dev：表示开发环境
  #test：表示测试环境
  #prod：表示生产环境
