spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # 注册当前feign服务到Eureka

# Feign 中使用熔断器
# 在Feign中不需要在Application上添加类似于Ribbon中使用的@EnableHystrix熔断器注解来启用熔断器
# Feign 是默认集成了熔断器的，但默认是关闭的。需要在配置文件中配置打开它:
feign:
  hystrix:
    enabled: true
