spring:
  application:
    name: hello-spring-cloud-service-admin

server:
  port: 8762

# 向eureka-server服务端注册当前服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # 要把当前服务注册到哪个地址

# 当 Client 向 Server(eureka-server) 注册时，它会提供一些元数据，例如主机和端口，URL，主页等。

# Eureka Server 从每个 Client 实例接收心跳消息。 如果心跳超时，则通常将该实例从注册 Server 中删除。

# 注意： 需要指明 spring.application.name，这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个 name
