spring:
  application:
    # 注意： 需要指明 spring.application.name，这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个 name
    name: hello-spring-cloud-service-admin
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8762

# 向eureka-server服务端注册当前服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # 要把当前服务注册到哪个地址
# 当 eureka client 向 eureka-server 注册时，它会提供一些数据:主机和端口，URL等

# Eureka Server 从每个 eureka Client 实例接收心跳消息。 如果心跳超时，则通常将该实例从注册 Server 中删除。