server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul: 
  #ignored-services: my-microservicecloud-dept-8001 # 忽略真实地址，只让虚拟地址访问
  prefix: /openPrefix # 用户访问地址的时候必须添加上前缀
  ignored-services: "*" # 忽略真实地址，只让虚拟地址访问
  routes: 
    mydept.serviceId: my-microservicecloud-dept-8001 # 真实地址
    mydept.path: /mydept/**   # 虚拟地址
 
info:
  app.name: xzj-microcloud-zuul-gateway-9527
  company.name: www.xzj.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}