server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul: 
  #ignored-services: microservicecloud-dept #忽略真实地址，只让虚拟地址访问
  prefix: /luo #访问地址前缀
  ignored-services: "*" #忽略真实地址，只让虚拟地址访问
  routes: 
    mydept.serviceId: microservicecloud-dept #真实地址
    mydept.path: /mydept/**   #虚拟地址
 
info:
  app.name: luo-microcloud
  company.name: www.luo.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$