server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.luo.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: my-microservicecloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB03
    username: root
    password: password
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: my-microservicecloud-provider-dept-instance-id-8003
    prefer-ip-address: true

info:
  app.name: my-microservicecloud-8003
  company.name: www.company.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}